### ISSUE TITLE
Homepage mockup design

### ISSUE THREAD

**Issue by yakkowu** [Padax/w-components#100]
According to issue #81, our official website of homepage mockup is on going.

And is being adjusted for some feedback, about v1:
1. Tutorial section's layout
2. Sequence of the team section
3. Features's item box
4. Replace Github icon
5. Language selector replace to the button behavior(just one click to change one of two languages)
6. Replace the teammate's portfolio pictures to grayscale type of portrait

→ Here's the currently file [in Figma](https://www.figma.com/file/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=181%3A91).

**Comment by yakkowu** [comment]
When the homepage mockup is passed, the next will be RWD parts.

**Comment by yakkowu** [comment]
## TASK COMPLETE!

For feedback, adjustments have been completed, and the layout details some other changes.
→ Here's the [prototype](https://www.figma.com/proto/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=181%3A91&scaling=min-zoom&page-id=121%3A91).

![Desktop - 1440](https://user-images.githubusercontent.com/46119829/132986839-5bef8ceb-7859-4f54-9f7b-0ace8b530b89.png)

> According to issue #81, our official website of homepage mockup is on going.
> 
> And is being adjusted for some feedback, about v1:
> 
> 1. Tutorial section's layout
> 2. Sequence of the team section
> 3. Features's item box
> 4. Replace Github icon
> 5. Language selector replace to the button behavior(just one click to change one of two languages)
> 6. Replace the teammate's portfolio pictures to grayscale type of portrait
> 
> → Here's the currently file [in Figma](https://www.figma.com/file/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=181%3A91).

**Comment by yakkowu** [comment]
Some adjustments and two types of RWD layout all completed, maybe we should need more common devices layout?

> By the way, if you want to switch to mobile preview, please check the top left of prototyping page 
and click the icon like this ↙︎

![image](https://user-images.githubusercontent.com/46119829/134783076-8ac8feba-5aab-4a8f-b7e9-a0df312067cc.png)

→ Here's the currently file [in Figma](https://www.figma.com/file/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=181%3A91).
→ Here's the [prototype](https://www.figma.com/proto/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=181%3A91&scaling=min-zoom&page-id=121%3A91).

### Desktop 1920px
![Desktop - 1920](https://user-images.githubusercontent.com/46119829/134782622-8f1f8fd9-22ab-4229-9a1c-db772689b9aa.png)
### Mobile 360px
![image](https://user-images.githubusercontent.com/46119829/134782669-e8fd65ec-3fb6-45f0-bfef-e2f05d8abed3.png)

> When the homepage mockup is passed, the next will be RWD parts.
> 
> * Mobile: 360px
> * Desktop: 1920px（consider the 1200px layout）

**Comment by yakkowu** [comment]
![image](https://user-images.githubusercontent.com/46119829/135763824-1c49c933-3872-48ed-85c7-fd86718ae0e1.png)
![image](https://user-images.githubusercontent.com/46119829/135763829-1e6c9ec2-38d9-4cce-b4af-9096bad532e9.png)
Added an design annotation to this [Figma](https://www.figma.com/file/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=121%3A91) file.
And the components that need to be customized on the Homepage have been completed.

**Comment by yakkowu** [comment]
FYI, more detailed about Components (Navbar, Text button with icon) will be in issue #88 and #101.

**Comment by cwpeng** [comment]
Move to website project.
