### ISSUE TITLE
First-added attribute on initial render shouldn't trigger update

### ISSUE THREAD

**Issue by nizniz187** [Padax/w-components#109]
Followed by commit #103 & MR #104.

**Comment by nizniz187** [comment]
I've tried to fix this issue by assigning initial value for all defined attributes before the init function triggered, but then bumped into the error _'Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes'_.
The [initial attribute assignment is actually limited from the spec](https://stackoverflow.com/a/54869164). So at this point I would make a conclusion that this issue is unable to fix. 
The best thing we can do may be putting a notice in our documentation:

>   **The update function will be triggered on initial rendering if any attribute is assigned.**

**Comment by nizniz187** [comment]
After a second thought, we could actually utilize the `connectedCallback` to identify whether the component is initialized. 
Because the order of triggering would be: `constructor` -> `attributeChangedCallback` -> `connectedCallback`.

**Comment by cwpeng** [comment]
I have tried connectedCallback last week, but failed. Maybe we can try again.
