### ISSUE TITLE
Consider using "filter" in the disabled input field

### ISSUE THREAD

**Issue by yakkowu** [Padax/w-components#129]
Use filter (brightness, contrast, saturation, ...) to adjust disabled filled input fields color, make special adjustment without changing the grayscale.

Some reference:  https://developer.mozilla.org/en-US/docs/Web/CSS/filter

**Comment by yakkowu** [comment]
@cwpeng 

There’re two places below, need to adjust disable state of this components:
- Text input
  ⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System?node-id=1055%3A216).
- Select
  ⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System?node-id=1211%3A342).

And, it's use the opacity() function: `filter: opacity(70%)` applies transparency.
Make it more dissimilar from the else states/types.

---

### Preview
#### Text input component
<img src="https://user-images.githubusercontent.com/46119829/148651877-2da5a2ad-c23a-4511-9820-e94c474ac387.png" width="50%">
<img src="https://user-images.githubusercontent.com/46119829/148651953-540e5539-481f-4ed0-a1cf-0cf01869e830.png" width="50%">

#### Select component
<img src="https://user-images.githubusercontent.com/46119829/148651885-dbd52c98-77ec-40ee-a4a7-129ba0afc0ad.png" width="50%">
<img src="https://user-images.githubusercontent.com/46119829/148652095-7aadadbb-83e5-4a7b-993d-6a44c56fea89.png" width="50%">

**Comment by nizniz187** [comment]
@cwpeng 
If there is no further question, please make revisions for `w-input` as designed.

**Comment by cwpeng** [comment]
Done.
