### ISSUE TITLE
Add laguage type property for Code

### ISSUE THREAD

**Issue by nizniz187** [Padax/w-components#130]
Auto-detecting is not always correct. For example, `npm install` is not detecting correctly.
That's why we need a property to let user assign the language.

**Comment by cwpeng** [comment]
How about this issue? Is it matter now?

**Comment by nizniz187** [comment]
I will implement it next.

**Comment by nizniz187** [comment]
Added an attribute `lang` for user to assign language manually. If this attribute is not set or set to empty, then an auto detection will be applied.

For example, this code is highlighted as HTML below in auto detection mode:
![image](https://user-images.githubusercontent.com/6836873/148671513-9cea7598-36f7-4c46-8823-670e6fb71eaf.png)
But if we assign the `lang` attribute to `javascript`, it would look slightly different:
![image](https://user-images.githubusercontent.com/6836873/148671644-54e86969-649b-46b6-b888-a021f47434f0.png)

For the initial problem this issue was intending to solve, the npm script looked like this in auto detection (obviously wrong):
![image](https://user-images.githubusercontent.com/6836873/148671711-0d58e6d6-25d2-46bc-867e-47a4f82e23a9.png)
Now it should be assigned correctly as `lang='shell'`:
![image](https://user-images.githubusercontent.com/6836873/148671745-1b71afac-ef35-447c-b85b-9ea66e3471cc.png)
which looks simply nothing highlighted, but is actually highlighted as designed (see the official demo code below.)
![image](https://user-images.githubusercontent.com/6836873/148671779-6e74d1a3-30e7-4b2e-a086-89770c286fb9.png)
In this situation, add a `$` sign in the front could make it look better :p
![image](https://user-images.githubusercontent.com/6836873/148671927-50df166c-bcbd-4f31-82a4-2c54d38babcc.png)

**Comment by nizniz187** [comment]
@cwpeng 
Please help review.

**Comment by cwpeng** [comment]
looks good.
