### ISSUE TITLE
Failed to load CSS style from our demo page.

### ISSUE THREAD

**Issue by yakkowu** [Padax/w-components#142]
Here's some screenshots below:

<img width="80%" alt="image" src="https://user-images.githubusercontent.com/46119829/156889311-83a10b1b-0f8b-4d91-8e6a-2d1b20ae8c97.png">

<img width="358" alt="image" src="https://user-images.githubusercontent.com/46119829/156889326-ce8e5e2a-6e4d-4dcc-9232-fb08314a763d.png">

**Comment by nizniz187** [comment]
This issue is seemed to be existing to me.
Please brief how you solve it, and assign other ones to review instead of just close it on your own. :)

**Comment by cwpeng** [comment]
It's due to ignored dist folder in our project. So, index.html hosted in GitHub Pages cannot load JavaScript code properly. Just add dist folder back to version control can solve this issue.

Link of icon font will be considered in another issue. #94
