### ISSUE TITLE
The Dark Mode - Shadows

### ISSUE THREAD

**Issue by yakkowu** [Padax/w-components#147]

**Comment by yakkowu** [comment]
# TASK COMPLETE!
<img width="90%" alt="image" src="https://user-images.githubusercontent.com/46119829/167310167-58cba738-cfbd-4969-ba88-3f86c4c1dbde.png">

Shadows in dark theme are different from light theme, using pure black (#000000) as the main color of shadow.
⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System-%5BWIP%5D?node-id=1351%3A387)

<img width="240" alt="image" src="https://user-images.githubusercontent.com/46119829/167310352-b08bf765-68f2-4653-9919-32b320f88ac0.png">

PS If you want to know more details about the shadow, please check #135  here.

**Comment by nizniz187** [comment]
Confirmed. This task will be taken over by developers to implement.

**Comment by nizniz187** [comment]
Demonstrated on 2022/09/01 with no further concern.
