### ISSUE TITLE
Add Basic Component - Code

### ISSUE THREAD

**Issue by nizniz187** [Padax/w-components#17]
Libraries for reference: Mozilla Ace, Google Prettier

**Comment by nizniz187** [comment]
### Pending Discussion

Candidate library: https://github.com/highlightjs/highlight.js/
We might need to discuss about how many / which languages we would like to support.
Also, we need to import build tool like webpack for package management & css import.

**Comment by nizniz187** [comment]
Imported languages: 34

![image](https://user-images.githubusercontent.com/6836873/127374278-2ac846e3-9d10-4609-b475-fd9eac68686b.png)

Applied theme: [GitHub Dark](https://github.com/highlightjs/highlight.js/blob/main/src/styles/github-dark.css)

**Comment by yakkowu** [comment]
@nizniz187 
Here is the conclusion of our meeting. It's the best choice to use GitHub Theme in the first version and then use an A11Y Theme when there is an A11Y version coming. (Dark & Light need to be able to correspond)

**Comment by nizniz187** [comment]
Close as the default theme set.
The further theme management will be tracked on issue #31 .
