### ISSUE TITLE
Add Integrated Component - Dialog

### ISSUE THREAD

**Issue by nizniz187** [Padax/w-components#25]

**Comment by yakkowu** [comment]
Working on how to make shadow effects of the box-shadow CSS property look more naturally, and define it.

**Comment by yakkowu** [comment]
# TASK COMPLETE!
<img src="https://user-images.githubusercontent.com/46119829/149634171-bd9aa86b-aeb2-4336-b1fd-5e236ea82e1b.png" width="100%">

In the last meeting, @cwpeng suggested that there should be a general style and an alert style, but I think it is enough to directly share the same set of components. Here I would like to propose that in addition to the user can customise the desired alert what the message is (like the Preview, you can check the last title of this comment, it's just changes color or add some emoji), it would be better to categorize it more formally in a common set of components called "Alerts" (Like this in [MUI](https://mui.com/components/alert/#main-content)) and [Bootstrap](https://getbootstrap.com/docs/5.1/components/alerts/).

If you still need to split the Dialog into "Warning", "General", "Successful", etc. into independent types, we can discuss it again 🙂

⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System-%5BWIP%5D?node-id=1316%3A453)

## Overview
### Types
Three of types:
- Standard
  - With all of these modules, Header and Footer.
- With Header
  - Only with Header module.
- With Footer
  - Only with Footer module.

By the way, the Dialog does not have only one Body module as any cases.
Therefore, it is not included in this types, just only three of them.

<img src="https://user-images.githubusercontent.com/46119829/149634689-c4b6e97d-4859-4f1e-9a67-2c59cc14ada7.png" width="80%">

### On the background
- Background without overlay
- Background with overlay
  - Overlay color is used the Grayscale 100
  - CSS: `background: rgba(34, 36, 38, 0.2); backdrop-filter: blur(5px); `

<img src="https://user-images.githubusercontent.com/46119829/149634758-3ada9096-ced7-45e1-96f3-a36f128ef008.png" width="80%">
<img src="https://user-images.githubusercontent.com/46119829/149634788-5cc98376-9830-4d00-a43a-ded4b7a63978.png" width="80%">

### Preview
<img src="https://user-images.githubusercontent.com/46119829/149634826-c9f52587-8ece-4837-affe-9845f9d338e1.png" width="80%">

**Comment by yakkowu** [comment]
# Update the Default sets
<img width="80%" alt="image" src="https://user-images.githubusercontent.com/46119829/153212598-4e344cf8-87cf-43dd-b680-a4c152a2ff44.png">

According to @cwpeng suggestion, here needs a default types: Confirm Dialog and Alert Dialog for this Dialog component.
⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System-%5BWIP%5D?node-id=1316%3A453).

**Comment by yakkowu** [comment]
> # Update the Default sets
> According to @cwpeng suggestion, here needs a default types: Confirm Dialog and Alert Dialog for this Dialog component. ⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System-%5BWIP%5D?node-id=1316%3A453).

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/46119829/153217702-a50dadad-c1eb-4cfd-b0ea-3c15c30e4147.png">

According to the previous comment, the default sets style are all added the view height and the background with overlay.

**Comment by cwpeng** [comment]
Add attributes:
- color: primary, critical and gray
- backdrop: normal, no-action and none.

Attributes stand for default settings for dialog, when open dialog by open method, user can pass settings to overwrite defaults dynamically.

**Comment by nizniz187** [comment]
Is this issue done and reviewed and ok to be closed?

**Comment by cwpeng** [comment]
I think it's done.
