### ISSUE TITLE
Define the default margins for all Heading & DisplayHeading components.

### ISSUE THREAD

**Issue by yakkowu** [Padax/w-components#42]
This’s according on issue  #38.

**Comment by yakkowu** [comment]
# TASK COMPLETE!

The left half is the spec of margin for each heading, and the right half is the basic layout of the preview.

  - Figma
    - no percentage option and units.
  - CSS
    - prefer percentage set.

⤷ Here's the currently file [in Figma](https://www.figma.com/file/5mAH9laNFI4q3oJeTN0sgq/Design-System?node-id=1137%3A434).

![image](https://user-images.githubusercontent.com/46119829/142249946-8d6243ae-f5d0-4468-b2fc-7e63bebf50e2.png)

![image](https://user-images.githubusercontent.com/46119829/142249657-be3c4fda-dd68-4e3e-85fd-f3dfcbf16e41.png)

![image](https://user-images.githubusercontent.com/46119829/142249752-dff6048e-3ef2-4440-93eb-9dbe52cc5568.png)

**Comment by yakkowu** [comment]
About the right half is the basic layout of preview, which is with margin collapsing behavior. 

Some reference: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

**Comment by nizniz187** [comment]
According to last meeting (&#35; 22), we use em to calculate margin size according to font size.
However, some proportions are indivisible, which produces some deviations between design docs & actual DOM margin size.
For example, DisplayHeading level 1 comes with font size 88px and margin top & bottom 24px. But 28/88 ~= 0.31818181... which is indivisible. If we use 0.318em as the value, the final margin size becomes 27.984px, which is near but not the exact 24px.

**Comment by yakkowu** [comment]
Got it! After thinking, I can accept these deviations, and also that we can keep the current calculation method and observe the results in other environments afterward.
