### ISSUE TITLE
Add routing component

### ISSUE THREAD

**Issue by nizniz187** [Padax/w-components#62]

**Comment by cwpeng** [comment]
1. Use template.
2. Support customized initializing and disposing process.

**Comment by cwpeng** [comment]
Fix Bugs:
1. Trigger dispose event every time even if user changes to any other spa-page.
2. Cannot show content in template if spa-page shows right after page loading.

**Comment by cwpeng** [comment]
More issue:
1. spa-page cannot trigger init event if showing right after page loading.
