### ISSUE TITLE
Design our official site

### ISSUE THREAD

**Issue by yakkowu** [Padax/w-components#81]
According to the conclusion of the weekly meeting(from @nizniz187 's proposal), I started to planning my part.

Here's my ideal design process map, which we can implement or discuss step by step:

- Brand Design
   - The name of the official project
   - #26 
   - Visual identity
   - Logo
- Define:
   - [Main point: W-Components Official Site(HackMD)](https://hackmd.io/iJQoZZjeRsCEEeMZebcYfw?view#%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E)
   - Sitemap
   - Content
   - Copywriting
   - Documentations
- Design:
   - Wireframe
   - Mockup

**Comment by yakkowu** [comment]
## INFORMATION UPDATE
I have organized & pre-wireframes some progress here, so that everyone can have a good start:

1. Competitive products: overview their website branding page
→ Here's the [current Figma file](https://www.figma.com/file/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=0%3A1).
![image](https://user-images.githubusercontent.com/46119829/127822249-6e1e207c-a499-421f-89f1-d2079e539a69.png)

2. Wireframe v0(Pre-built content and layouts)
→ Here's the [current Figma file](https://www.figma.com/file/wBCzyCTlWrXBAXoPj2lF8b/Official-Site?node-id=7%3A10)
![image](https://user-images.githubusercontent.com/46119829/127823735-1fad879e-b9d3-4ee5-a1a2-d134be822655.png)
---
- Pending main points for discussion:
1. The Hero Section
   - I have sorted out several copywriting models from competing products for your reference and thoughts together.
![image](https://user-images.githubusercontent.com/46119829/127824814-a1786753-1313-436d-a557-c460e4426198.png)

2. The Top Features Section
   - At present, I have sorted out a few first:
     - Light‑weight（輕量化）
     - Intuitional（直觀使用）
     - Themeable（主題化，可客製化）
     - Accessible（無障礙）
     - Light and Dark UI（淺色與深色模式介面）
![image](https://user-images.githubusercontent.com/46119829/127827702-cd8e8172-16bc-4ef2-b8c3-8b390e38b4aa.png)

**Comment by cwpeng** [comment]
Completed wording of hero section and features.

**Comment by yakkowu** [comment]
According to the conclusion of the meeting, we(@cwpeng @nizniz187 @yakkowu ) need to re-proposal the wording of hero section, and post it on HackMD, before discussing it at the meeting next week.

Here's our post it are:
→ [HackMD](https://hackmd.io/iJQoZZjeRsCEEeMZebcYfw?view#%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E)
![image](https://user-images.githubusercontent.com/46119829/129452860-0086ba13-47c7-408f-b2cd-2750adc208eb.png)

**Comment by cwpeng** [comment]
Move to website project.
