### ISSUE TITLE
Never use page based relative path

### ISSUE THREAD

**Issue by cwpeng** [Padax/w-components#94]
For example, path to stylesheet cannot relative to homepage path.

**Comment by cwpeng** [comment]
Change css file to js file, interpret css code to js templated string is the best way to import css theme.

Other two ways:
1. Import css by absolute path refer to an online resource.
2. Leave css file path for user, but it is not so good on criteria of simplicity and easy-to-use.

**Comment by cwpeng** [comment]
Icon Font links meet path issue as the same as stylesheet link.

**Comment by nizniz187** [comment]
So it looks like we still use live link for both stylesheet js files & iconfont files? (ie. rely on the resources put on our github page.)
What if the users do want to use our stylesheets, but rather maintain files on their own? Download to local manually and put somewhere is such an old-school way.
For stylesheets, I prefer bundle it along with our library code. (See [how to import Bootstrap styles](https://getbootstrap.com/docs/5.0/getting-started/webpack/#importing-styles).)
For iconfont, we can bundle it along with our library too, as [Bootstrap](https://getbootstrap.com/docs/5.0/extend/icons/#bootstrap-icons) does, or separate out as an independent package as [FontAwesome](https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react) does if the bundle size is too large.
For the later option, it is related to #74 .

**Comment by cwpeng** [comment]
I don't get your points very well.

**Comment by nizniz187** [comment]
And? Please advise the next step.

**Comment by cwpeng** [comment]
For efficiency, I think we should talk directly.

**Comment by nizniz187** [comment]
The stylesheets now are imported as JS, and the iconfonts need to be imported manually either by external link or physical files in a relative path.
Both are acceptable but maybe not the ideal ways.
This topic should be re-considered with the issues #59 and #73.
